import{useState,useEffect,useMemo}from"react";
import BiensPage from"./BiensPage";
const TL=[{id:"airbnb",label:"Airbnb/Saisonnier",emoji:"🏖",rc:"Loyer Airbnb / saisonnier"},{id:"meuble",label:"Bail meublé (LMNP)",emoji:"🛋",rc:"Loyer meublé"},{id:"nu",label:"Bail nu",emoji:"🏠",rc:"Loyer nu"},{id:"professionnel",label:"Bail professionnel équipé",emoji:"💼",rc:"Loyer professionnel équipé"},{id:"commercial",label:"Bail commercial",emoji:"🏪",rc:"Loyer commercial"},{id:"parking",label:"Parking/Cave",emoji:"🅿️",rc:"Loyer parking"}];
const LM=Object.fromEntries(TL.map(t=>[t.id,t]));
const LC={airbnb:{bg:"#eaf4fb",tx:"#2471a3"},meuble:{bg:"#e6efe9",tx:"#2d5b3d"},nu:{bg:"#eeebe3",tx:"#6b8c74"},professionnel:{bg:"#fef9e7",tx:"#b7860b"},commercial:{bg:"#fdf2e9",tx:"#ca6f1e"},parking:{bg:"#f4ecf7",tx:"#7d3c98"}};
const TB=["Résidentiel nu","Résidentiel meublé","Professionnel équipé","Commercial","Mixte","Parking/Cave","Immeuble (multi-lots)"];
const RG=["Nu / Revenus fonciers (2044)","LMNP / BIC réel","LMP / BIC réel","Micro-foncier","Micro-BIC","IS - SARL de famille","IS - SARL/SAS classique"];
const CR=["Loyer nu","Loyer meublé","Loyer Airbnb / saisonnier","Loyer professionnel équipé","Loyer commercial","Loyer parking","Charges récupérées","Dépôt de garantie encaissé","Remboursement sinistre","Subvention / aide","Autre revenu"];
const CC=["Frais de gestion / conciergerie","Charges de copropriété","Assurance habitation","Assurance loyers impayés","Assurance emprunteur","Assurance PNO","Frais de ménage et entretien","Frais plateformes (Airbnb, Booking...)","Honoraires comptable","Abonnement électricité","Abonnement internet/téléphone","Abonnement eau/gaz","Taxe foncière","Taxe d'habitation","Taxe de séjour","CFE","Charges sociales SSI","Petits travaux (moins 600 euros)","Petit mobilier (moins 600 euros)","Travaux + 600 euros","Mobilier + 600 euros","Crédit immobilier - capital","Crédit immobilier - intérêts","Parties communes","Dépenses diverses","Autre charge"];
const MF=["Janvier","Février","Mars","Avril","Mai","Juin","Juillet","Août","Septembre","Octobre","Novembre","Décembre"];
const AN=Array.from({length:6},(_,i)=>new Date().getFullYear()-i);
const KY="corenta-immo-v5";
const eu=n=>Number(n||0).toLocaleString("fr-FR",{style:"currency",currency:"EUR"});
const pt=n=>`${Number(n||0).toFixed(2)} %`;
const fd=d=>{if(!d)return"—";const[y,m,j]=d.split("-");return`${j}/${m}/${y}`;};
const nw=()=>new Date().toISOString().slice(0,10);
const ui=()=>Date.now()+Math.random().toString(36).slice(2);
const CY=new Date().getFullYear();
function ld(){try{return JSON.parse(localStorage.getItem(KY))||it();}catch{return it();}}
function it(){return{biens:[],transactions:[],locataires:[],lots:[],documents:[]};}
const C={g:"#2d5b3d",gl:"#3d7a52",gp:"#e6efe9",cr:"#f7f4ee",cr2:"#eeebe3",tx:"#1a2a1f",tm:"#6b8c74",rd:"#c0392b",rp:"#fdecea",bl:"#2471a3",bp:"#eaf4fb",gd:"#b7860b",dp:"#fef9e7",wh:"#ffffff",br:"#dde8e0"};
const Ip=({lb,...p})=>(<div style={{marginBottom:12}}>{lb&&<label style={{display:"block",fontSize:11,fontWeight:700,color:C.gl,textTransform:"uppercase",letterSpacing:".05em",marginBottom:4}}>{lb}</label>}<input style={{width:"100%",padding:"9px 11px",border:`1.5px solid ${C.br}`,borderRadius:8,fontSize:14,fontFamily:"inherit",color:C.tx,background:C.cr,outline:"none",boxSizing:"border-box"}} {...p}/></div>);
const Sl=({lb,children,...p})=>(<div style={{marginBottom:12}}>{lb&&<label style={{display:"block",fontSize:11,fontWeight:700,color:C.gl,textTransform:"uppercase",letterSpacing:".05em",marginBottom:4}}>{lb}</label>}<select style={{width:"100%",padding:"9px 11px",border:`1.5px solid ${C.br}`,borderRadius:8,fontSize:14,fontFamily:"inherit",color:C.tx,background:C.cr,outline:"none",boxSizing:"border-box"}} {...p}>{children}</select></div>);
const Bt=({v="p",ch,sx,...p})=>{const S={p:{background:C.g,color:"#fff",border:"none"},s:{background:"transparent",color:C.g,border:`1.5px solid ${C.g}`},d:{background:"transparent",color:C.rd,border:`1.5px solid ${C.rd}`},g:{background:C.gp,color:C.g,border:"none"}};return<button style={{padding:"9px 18px",borderRadius:9,fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:"inherit",...S[v],...sx}} {...p}>{ch}</button>;};
const Cd=({ch,sx})=><div style={{background:C.wh,borderRadius:14,padding:"18px 20px",marginBottom:14,boxShadow:"0 1px 10px rgba(45,91,61,.07)",border:`1px solid ${C.br}`,...sx}}>{ch}</div>;
const Bg=({bg=C.gp,tc=C.g,ch})=><span style={{display:"inline-block",padding:"2px 9px",borderRadius:20,background:bg,color:tc,fontSize:11,fontWeight:700}}>{ch}</span>;
const Sb=({lb,vl,co})=><div style={{textAlign:"center",padding:"8px 4px"}}><div style={{fontSize:20,fontWeight:800,color:co||C.g,lineHeight:1.1}}>{vl}</div><div style={{fontSize:10,color:"rgba(255,255,255,.6)",marginTop:3,textTransform:"uppercase",letterSpacing:".06em"}}>{lb}</div></div>;
const Dv=()=><div style={{height:1,background:C.br,margin:"12px 0"}}/>;
const St=({ch})=><div style={{fontSize:11,fontWeight:700,color:C.gl,textTransform:"uppercase",letterSpacing:".07em",marginBottom:10}}>{ch}</div>;
const Kv=({k,v})=><div style={{display:"flex",justifyContent:"space-between",padding:"5px 0",borderBottom:`1px solid ${C.br}`,fontSize:13}}><span style={{color:C.tm}}>{k}</span><span style={{fontWeight:700}}>{v}</span></div>;
const Fl=({lb,vl,bd,in:ind,mt,co})=><div style={{display:"flex",justifyContent:"space-between",padding:"5px 0",paddingLeft:ind?12:0,borderBottom:`1px solid ${C.br}`}}><span style={{fontSize:13,color:mt?C.tm:C.tx}}>{lb}</span><span style={{fontSize:13,fontWeight:bd?800:600,color:co||(mt?C.tm:C.tx)}}>{vl}</span></div>;
function st(txs){const rv=txs.filter(t=>t.sens==="revenu");const ch=txs.filter(t=>t.sens==="charge");const R=rv.reduce((s,t)=>s+t.montant,0);const CH=ch.reduce((s,t)=>s+t.montant,0);const lo=rv.filter(t=>t.categorie?.toLowerCase().includes("loyer")).reduce((s,t)=>s+t.montant,0);const dd=ch.filter(t=>t.categorie!=="Crédit immobilier - capital").reduce((s,t)=>s+t.montant,0);const cp=ch.filter(t=>t.categorie==="Crédit immobilier - capital").reduce((s,t)=>s+t.montant,0);const it=ch.filter(t=>t.categorie==="Crédit immobilier - intérêts").reduce((s,t)=>s+t.montant,0);return{rv,ch,R,CH,lo,dd,cp,it,cf:R-CH,rs:lo-dd};}
function cIS(r){if(r<=0)return 0;return Math.min(r,42500)*0.15+Math.max(0,r-42500)*0.25;}

export default function App(){
  const[da,sD]=useState(ld);
  const[pg,sP]=useState("dash");
  const[bId,sBi]=useState(null);
  const[lId,sLi]=useState(null);
  const[sb,sSb]=useState("apercu");
  const[an,sA]=useState(CY);
  const[to,sT]=useState(null);
  const[mo,sM]=useState(null);
  const[fm,sF]=useState({});
  useEffect(()=>{try{localStorage.setItem(KY,JSON.stringify(da));}catch{}},[da]);
  const bn=useMemo(()=>da.biens.find(b=>b.id===bId),[da.biens,bId]);
  const im=bn?.type==="Immeuble (multi-lots)";
  const lb=useMemo(()=>(da.lots||[]).filter(l=>l.bienId===bId),[da.lots,bId]);
  const lt=useMemo(()=>(da.lots||[]).find(l=>l.id===lId),[da.lots,lId]);
  function tst(msg,t="ok"){sT({msg,t});setTimeout(()=>sT(null),3000);}
  function oM(tp,df={}){sM(tp);sF(df);}
  function cM(){sM(null);sF({});}
  function sf(k,v){sF(f=>({...f,[k]:v}));}
  const txO=(bi,li,yr)=>da.transactions.filter(t=>t.bienId===bi&&(li!==undefined?t.lotId===li:true)&&(yr?String(t.date).startsWith(String(yr)):true));
  const stB=useMemo(()=>st(txO(bId,undefined,an)),[da.transactions,bId,an]);
  const stL=useMemo(()=>st(txO(bId,lId,an)),[da.transactions,bId,lId,an]);
  function sBn(){if(!fm.nom?.trim())return;const b={...fm,valeurAchat:parseFloat(fm.valeurAchat||0)};if(mo==="eB"){sD(d=>({...d,biens:d.biens.map(x=>x.id===bId?{...x,...b}:x)}));tst("Bien mis à jour");}else{const nb={id:ui(),...b};sD(d=>({...d,biens:[...d.biens,nb]}));tst("Bien ajouté");}cM();}
  function sLt(){if(!fm.nom?.trim()||!fm.typeLot)return;const l={...fm,loyer:parseFloat(fm.loyer||0),surface:parseFloat(fm.surface||0),valeurEstimee:parseFloat(fm.valeurEstimee||0)};if(mo==="eLt"){sD(d=>({...d,lots:d.lots.map(x=>x.id===lId?{...x,...l}:x)}));tst("Lot mis à jour");}else{const nl={id:ui(),bienId:bId,...l};sD(d=>({...d,lots:[...(d.lots||[]),nl]}));tst("Lot ajouté");}cM();}
  function dLt(id){sD(d=>({...d,lots:(d.lots||[]).filter(l=>l.id!==id),transactions:d.transactions.filter(t=>t.lotId!==id)}));if(lId===id){sLi(null);sSb("lots");sP("bien");}tst("Lot supprimé","err");}
  function sTx(){if(!fm.montant||!fm.date||!fm.categorie)return;if(fm.id){sD(d=>({...d,transactions:d.transactions.map(t=>t.id===fm.id?{...t,...fm,montant:parseFloat(fm.montant)}:t)}));tst("Mis à jour");cM();}else{const tx={id:ui(),bienId:bId,lotId:fm.lotId||null,...fm,montant:parseFloat(fm.montant)};sD(d=>({...d,transactions:[...d.transactions,tx]}));tst("Enregistré");sF(f=>({...f,montant:"",description:"",ref:""}));}}
  function sLc(){if(!fm.nom?.trim())return;const l={id:ui(),bienId:bId,lotId:fm.lotId||null,...fm};sD(d=>({...d,locataires:[...d.locataires,l]}));tst("Locataire ajouté");cM();}
  function dTx(id){sD(d=>({...d,transactions:d.transactions.filter(t=>t.id!==id)}));tst("Supprimé","err");}
  function eTx(t){oM("aTx",{...t});}
  function dLc(id){sD(d=>({...d,locataires:d.locataires.filter(l=>l.id!==id)}));tst("Supprimé","err");}
  function dBn(id){sD(d=>({...d,biens:d.biens.filter(b=>b.id!==id),transactions:d.transactions.filter(t=>t.bienId!==id),locataires:d.locataires.filter(l=>l.bienId!==id),lots:(d.lots||[]).filter(l=>l.bienId!==id)}));sP("dash");sBi(null);tst("Bien supprimé","err");}
  const aA=da.transactions.filter(t=>String(t.date).startsWith(String(an)));
  const tRG=aA.filter(t=>t.sens==="revenu").reduce((s,t)=>s+t.montant,0);
  const tCG=aA.filter(t=>t.sens==="charge").reduce((s,t)=>s+t.montant,0);
  const NI=[["apercu","📊 Aperçu"],["lots","🏢 Lots"],["revenus","💰 Revenus"],["charges","📉 Charges"],["locataires","👤 Locataires"],["tva","🔵 TVA"],["docs","📎 Documents"],["fiscal","📋 Déclaration"],["infos","⚙️ Infos"]];
  const NB=[["apercu","📊 Aperçu"],["revenus","💰 Revenus"],["charges","📉 Charges"],["locataires","👤 Locataires"],["tva","🔵 TVA"],["docs","📎 Documents"],["fiscal","📋 Déclaration"],["infos","⚙️ Infos"]];
  const NL=[["apercu_l","📊 Aperçu"],["rev_l","💰 Revenus"],["chg_l","📉 Charges"],["loc_l","👤 Locataire"],["docs_l","📎 Documents"],["infos_l","⚙️ Infos"]];

  return(<div style={{fontFamily:"'Figtree',sans-serif",background:C.cr,minHeight:"100vh",color:C.tx}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Figtree:wght@300;400;600;700;800;900&display=swap');*{box-sizing:border-box;margin:0}button:hover{opacity:.85}input:focus,select:focus{border-color:${C.g}!important;box-shadow:0 0 0 3px ${C.gp}}@keyframes fu{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}@keyframes ti{from{opacity:0;transform:translateX(-50%) translateY(14px)}to{opacity:1;transform:translateX(-50%) translateY(0)}}.hov:hover{box-shadow:0 4px 20px rgba(45,91,61,.14)!important;transform:translateY(-2px)}.tr:hover{background:${C.gp}!important}`}</style>

    <div style={{background:C.g,padding:"16px 20px",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
      <div onClick={()=>{sP("dash");sBi(null);sLi(null);}} style={{cursor:"pointer"}}>
        <div style={{fontSize:22,fontWeight:900,color:"#fff"}}><span style={{fontWeight:300}}>Co</span>renta <span style={{fontSize:12,fontWeight:400,opacity:.6}}>Immobilier</span></div>
        <div style={{fontSize:11,color:"rgba(255,255,255,.6)"}}>Gestion · Rentabilité · Déclaration fiscale</div>
      </div>
      <select value={an} onChange={e=>sA(Number(e.target.value))} style={{padding:"6px 10px",borderRadius:8,border:"none",background:"rgba(255,255,255,.15)",color:"#fff",fontSize:13,fontWeight:700,fontFamily:"inherit",cursor:"pointer"}}>{AN.map(a=><option key={a} value={a} style={{color:C.tx}}>{a}</option>)}</select>
    </div>

    <div style={{background:C.wh,borderBottom:`2px solid ${C.br}`,display:"flex",gap:2,padding:"8px 14px 0",overflowX:"auto"}}>
      {[["dash","🏘 Tableau de bord"],["biens","🏠 Mes biens"],bn&&["bien",`🏠 ${bn.nom}`],lt&&["lot",`${LM[lt.typeLot]?.emoji||""} ${lt.nom}`]].filter(Boolean).map(([k,l])=>(
        <button key={k} onClick={()=>{if(k==="bien"){sP("bien");sLi(null);sSb(im?"lots":"apercu");}else sP(k);}} style={{padding:"7px 14px",border:"none",borderRadius:"8px 8px 0 0",fontWeight:700,fontSize:13,fontFamily:"inherit",cursor:"pointer",whiteSpace:"nowrap",background:pg===k?C.g:"transparent",color:pg===k?"#fff":C.g}}>{l}</button>
      ))}
      <div style={{flex:1}}/>
      {pg==="dash"&&<Bt v="g" sx={{marginBottom:4,fontSize:12}} ch="+ Nouveau bien" onClick={()=>oM("aBn",{type:TB[0],regime:RG[0]})}/>}
      {pg==="bien"&&im&&sb==="lots"&&<Bt v="g" sx={{marginBottom:4,fontSize:12}} ch="+ Nouveau lot" onClick={()=>oM("aLt",{typeLot:"meuble"})}/>}
    </div>

    <div style={{maxWidth:800,margin:"0 auto",padding:"18px 14px 70px"}}>

      {pg==="dash"&&(<>
        <Cd sx={{background:`linear-gradient(135deg,${C.g},${C.gl})`,border:"none"}} ch={<><div style={{fontSize:11,fontWeight:700,color:"rgba(255,255,255,.65)",textTransform:"uppercase",letterSpacing:".07em",marginBottom:10}}>Synthèse {an}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr 1fr",gap:4}}><Sb lb="Biens" vl={da.biens.length} co="#fff"/><Sb lb="Revenus" vl={eu(tRG)} co="#a8d5b5"/><Sb lb="Charges" vl={eu(tCG)} co="#f5a89a"/><Sb lb="Cashflow" vl={eu(tRG-tCG)} co={tRG-tCG>=0?"#a8d5b5":"#f5a89a"}/></div></>}/>
        {da.biens.length===0?<Cd sx={{textAlign:"center",padding:"48px 20px"}} ch={<><div style={{fontSize:48,marginBottom:12}}>🏡</div><div style={{fontWeight:700,fontSize:17,marginBottom:6}}>Aucun bien enregistré</div><div style={{color:C.tm,fontSize:13,marginBottom:20}}>Ajoutez un bien simple ou un immeuble multi-lots.</div><Bt ch="+ Ajouter un bien" onClick={()=>oM("aBn",{type:TB[0],regime:RG[0]})}/></>}/>
        :da.biens.map(b=>{
          const tB=da.transactions.filter(t=>t.bienId===b.id&&String(t.date).startsWith(String(an)));
          const rv=tB.filter(t=>t.sens==="revenu").reduce((s,t)=>s+t.montant,0);
          const ch=tB.filter(t=>t.sens==="charge").reduce((s,t)=>s+t.montant,0);
          const lB=(da.lots||[]).filter(l=>l.bienId===b.id);
          const im2=b.type==="Immeuble (multi-lots)";
          return(<div key={b.id} className="hov" onClick={()=>{sBi(b.id);sSb(im2?"lots":"apercu");sP("bien");sLi(null);}} style={{background:C.wh,borderRadius:14,padding:"16px 20px",marginBottom:12,boxShadow:"0 1px 10px rgba(45,91,61,.07)",border:`1px solid ${C.br}`,cursor:"pointer",transition:"all .18s",animation:"fu .3s"}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:12}}>
              <div style={{flex:1}}>
                <div style={{display:"flex",gap:8,alignItems:"center",marginBottom:4}}><span style={{fontSize:20}}>{im2?"🏢":"🏠"}</span><span style={{fontWeight:800,fontSize:16}}>{b.nom}</span></div>
                {b.adresse&&<div style={{fontSize:12,color:C.tm,marginBottom:6}}>📍 {b.adresse}</div>}
                <div style={{display:"flex",gap:5,flexWrap:"wrap"}}><Bg bg={C.gp} tc={C.g} ch={b.type}/>{im2&&<Bg bg={C.bp} tc={C.bl} ch={`${lB.length} lot${lB.length!==1?"s":""}`}/>{im2&&[...new Set(lB.map(l=>l.typeLot))].map(tp=>{const i=LM[tp];const c=LC[tp];return i?<Bg key={tp} bg={c?.bg} tc={c?.tx} ch={`${i.emoji} ${i.label.split(" ")[0]}`}/>:null;})}</div>
              </div>
              <div style={{textAlign:"right",flexShrink:0}}><div style={{fontSize:9,color:C.tm,textTransform:"uppercase"}}>Cashflow {an}</div><div style={{fontSize:22,fontWeight:900,color:rv-ch>=0?C.g:C.rd}}>{eu(rv-ch)}</div><div style={{fontSize:11,color:C.tm}}>{eu(rv)} rev · {eu(ch)} chg</div></div>
            </div>
          </div>);
        })}
      </>)}

      {pg==="biens"&&<BiensPage/>}
      {pg==="bien"&&bn&&(<>
        <div style={{display:"flex",gap:4,marginBottom:16,flexWrap:"wrap"}}>{(im?NI:NB).map(([k,l])=>(<button key={k} onClick={()=>sSb(k)} style={{padding:"6px 12px",borderRadius:8,border:`1.5px solid ${sb===k?C.g:C.br}`,background:sb===k?C.g:C.wh,color:sb===k?"#fff":C.tx,fontWeight:600,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>{l}</button>))}</div>

        {sb==="lots"&&im&&(<>
          <Cd sx={{background:`linear-gradient(135deg,${C.g},${C.gl})`,border:"none"}} ch={<><div style={{fontSize:11,fontWeight:700,color:"rgba(255,255,255,.65)",textTransform:"uppercase",letterSpacing:".07em",marginBottom:8}}>Immeuble — {an}</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4}}><Sb lb="Lots" vl={lb.length} co="#fff"/><Sb lb="Revenus" vl={eu(stB.R)} co="#a8d5b5"/><Sb lb="Charges" vl={eu(stB.CH)} co="#f5a89a"/><Sb lb="Cashflow" vl={eu(stB.cf)} co={stB.cf>=0?"#a8d5b5":"#f5a89a"}/></div></>}/>
          {lb.length>0&&<Cd ch={<><St ch="Composition"/><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:8,marginBottom:12}}>{TL.map(tp=>{const n=lb.filter(l=>l.typeLot===tp.id).length;if(!n)return null;const su=lb.filter(l=>l.typeLot===tp.id).reduce((s,l)=>s+(l.surface||0),0);const lo=lb.filter(l=>l.typeLot===tp.id).reduce((s,l)=>s+(l.loyer||0),0);const c=LC[tp.id];return(<div key={tp.id} style={{background:c?.bg,borderRadius:10,padding:"10px 12px"}}><div style={{fontSize:20,marginBottom:4}}>{tp.emoji}</div><div style={{fontWeight:800,fontSize:14,color:c?.tx}}>{n} lot{n>1?"s":""}</div><div style={{fontSize:11,color:C.tm}}>{tp.label.split("(")[0].trim()}</div>{su>0&&<div style={{fontSize:11,color:C.tm}}>{su} m²</div>}{lo>0&&<div style={{fontSize:12,fontWeight:700,color:c?.tx,marginTop:2}}>{eu(lo)}/mois</div>}</div>);})}</div><div style={{padding:"8px 12px",background:C.gp,borderRadius:8,display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:13,fontWeight:600}}>Loyer mensuel total</span><span style={{fontSize:15,fontWeight:800,color:C.g}}>{eu(lb.reduce((s,l)=>s+(l.loyer||0),0))}/mois</span></div><div style={{padding:"8px 12px",background:C.cr2,borderRadius:8,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:13,fontWeight:600}}>Surface totale</span><span style={{fontSize:15,fontWeight:800}}>{lb.reduce((s,l)=>s+(l.surface||0),0)} m²</span></div></>}/>}
          {lb.length===0?<Cd sx={{textAlign:"center",padding:"40px 20px"}} ch={<><div style={{fontSize:40,marginBottom:10}}>🏢</div><div style={{fontWeight:700,fontSize:15,marginBottom:6}}>Aucun lot enregistré</div><div style={{color:C.tm,fontSize:13,marginBottom:18}}>Ajoutez appartements, locaux et parkings.</div><Bt ch="+ Ajouter un lot" onClick={()=>oM("aLt",{typeLot:"meuble"})}/></>}/>
          :lb.map(l=>{const sL=st(txO(bId,l.id,an));const lL=da.locataires.filter(x=>x.lotId===l.id);const tp=LM[l.typeLot];const c=LC[l.typeLot];const rd=l.valeurEstimee>0?((l.loyer||0)*12/l.valeurEstimee*100):0;return(<div key={l.id} className="hov" onClick={()=>{sLi(l.id);sSb("apercu_l");sP("lot");}} style={{background:C.wh,borderRadius:13,padding:"14px 18px",marginBottom:10,boxShadow:"0 1px 8px rgba(45,91,61,.06)",border:`1.5px solid ${c?.bg||C.br}`,cursor:"pointer",transition:"all .18s"}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:10}}>
              <div style={{flex:1}}><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:5}}><span style={{fontSize:22}}>{tp?.emoji||"🏠"}</span><div><div style={{fontWeight:800,fontSize:15}}>{l.nom}</div><div style={{fontSize:11,color:C.tm}}>{[l.etage&&`Étage ${l.etage}`,l.surface&&`${l.surface} m²`,l.nbPieces&&`${l.nbPieces} p.`].filter(Boolean).join(" · ")}</div></div></div><div style={{display:"flex",gap:5,flexWrap:"wrap"}}><Bg bg={c?.bg} tc={c?.tx} ch={tp?.label}/>{lL.length>0?<Bg bg={C.dp} tc={C.gd} ch={lL[0].nom}/>:<Bg bg={C.rp} tc={C.rd} ch="Vacant"/>}{rd>0&&<Bg bg={C.gp} tc={C.g} ch={`Rdt ${pt(rd)}`}/>}</div></div>
              <div style={{textAlign:"right",flexShrink:0}}>{l.loyer>0&&<div style={{fontSize:15,fontWeight:800,color:C.g}}>{eu(l.loyer)}<span style={{fontSize:11,fontWeight:400}}>/mois</span></div>}<div style={{fontSize:11,color:sL.cf>=0?C.g:C.rd,fontWeight:700}}>CF {an} : {eu(sL.cf)}</div><div style={{fontSize:10,color:C.tm}}>{eu(sL.R)} / {eu(sL.CH)}</div></div>
            </div>
          </div>);})}
          <Bt ch="+ Ajouter un lot" onClick={()=>oM("aLt",{typeLot:"meuble"})} sx={{marginTop:4}}/>
        </>)}

        {sb==="apercu"&&(<>
          <Cd sx={{background:`linear-gradient(135deg,${C.g},${C.gl})`,border:"none"}} ch={<><div style={{fontSize:11,fontWeight:700,color:"rgba(255,255,255,.65)",textTransform:"uppercase",letterSpacing:".07em",marginBottom:8}}>Performance {an}</div><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:4}}><Sb lb="Revenus" vl={eu(stB.R)} co="#a8d5b5"/><Sb lb="Charges" vl={eu(stB.CH)} co="#f5a89a"/><Sb lb="Cashflow" vl={eu(stB.cf)} co={stB.cf>=0?"#a8d5b5":"#f5a89a"}/><Sb lb="Résultat" vl={eu(stB.rs)} co={stB.rs>=0?"#a8d5b5":"#f5a89a"}/></div></>}/>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:14}}>
            <Cd sx={{margin:0}} ch={<><St ch="Rentabilité"/>{[["Valeur d'achat",eu(bn.valeurAchat)],["Rdt brut",pt(bn.valeurAchat>0?(stB.lo/bn.valeurAchat*100):0)],["Rdt net",pt(bn.valeurAchat>0?((stB.lo-stB.dd)/bn.valeurAchat*100):0)],["CF/mois",eu(stB.cf/12)]].map(([k,v])=><Kv key={k} k={k} v={v}/>)}</>}/>
            <Cd sx={{margin:0}} ch={<><St ch="Crédit"/>{[["Capital remboursé",eu(stB.cp)],["Intérêts payés",eu(stB.it)],["Annuité totale",eu(stB.cp+stB.it)],["Intérêts déductibles","✓ Oui"]].map(([k,v])=><Kv key={k} k={k} v={v}/>)}</>}/>
          </div>
          {im&&lb.length>0&&<Cd ch={<><St ch={`Cashflow par lot — ${an}`}/>{lb.map(l=>{const sL=st(txO(bId,l.id,an));const tp=LM[l.typeLot];const c=LC[l.typeLot];return(<div key={l.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"7px 0",borderBottom:`1px solid ${C.br}`,gap:8}}><div style={{display:"flex",gap:8,alignItems:"center",flex:1}}><span>{tp?.emoji}</span><span style={{fontSize:13,fontWeight:600}}>{l.nom}</span><Bg bg={c?.bg} tc={c?.tx} ch={tp?.label.split(" ")[0]}/></div><div style={{textAlign:"right"}}><span style={{fontSize:13,fontWeight:800,color:sL.cf>=0?C.g:C.rd}}>{eu(sL.cf)}</span><div style={{fontSize:10,color:C.tm}}>{eu(sL.R)} / {eu(sL.CH)}</div></div></div>);})}</>}/>}
          <div style={{display:"flex",gap:8}}><Bt ch="+ Revenu" onClick={()=>oM("aTx",{sens:"revenu",date:nw(),categorie:CR[0],lotId:""})}/><Bt v="s" ch="+ Charge" onClick={()=>oM("aTx",{sens:"charge",date:nw(),categorie:CC[0],lotId:""})}/></div>
        </>)}

        {(sb==="revenus"||sb==="charges")&&<TxSec sx={sb==="revenus"?"revenu":"charge"} txs={sb==="revenus"?stB.rv:stB.ch} tot={sb==="revenus"?stB.R:stB.CH} dd={stB.dd} cp={stB.cp} ls={im?lb:[]} oA={()=>oM("aTx",{sens:sb==="revenus"?"revenu":"charge",date:nw(),categorie:sb==="revenus"?CR[0]:CC[0],lotId:""})} oD={dTx} oE={eTx} an={an}/>}
        {sb==="locataires"&&(<><div style={{display:"flex",justifyContent:"flex-end",marginBottom:10}}><Bt ch="+ Ajouter locataire" onClick={()=>oM("aLc",{typeContrat:"Bail meublé",statut:"Actif",lotId:""})}/></div>{da.locataires.filter(l=>l.bienId===bId).length===0?<Cd sx={{textAlign:"center",padding:"36px"}} ch={<><div style={{fontSize:32}}>👤</div><div style={{color:C.tm}}>Aucun locataire.</div></>}/>:da.locataires.filter(l=>l.bienId===bId).map(l=><LcCard key={l.id} l={l} lt={(da.lots||[]).find(x=>x.id===l.lotId)} oD={dLc}/>)}</>)}
        {sb==="tva"&&<TvaSec txs={da.transactions.filter(t=>t.bienId===bId)} an={an}/>}
        {sb==="docs"&&<DocSec bId={bId} lId={null} txs={da.transactions.filter(t=>t.bienId===bId)} da={da} sD={sD} ui_={ui} ts={tst}/>}
        {sb==="fiscal"&&<FiscSec bn={bn} stB={stB} an={an}/>}
        {sb==="infos"&&<Cd ch={<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={{fontWeight:800,fontSize:16}}>{bn.nom}</div><div style={{display:"flex",gap:8}}><Bt v="g" sx={{fontSize:12}} ch="✏️ Modifier" onClick={()=>oM("eB",{...bn})}/><Bt v="d" sx={{fontSize:12}} ch="Supprimer" onClick={()=>{if(window.confirm("Supprimer ce bien ?"))dBn(bId);}}/></div></div>{[["Adresse",bn.adresse],["Type",bn.type],["Régime fiscal",bn.regime],["Valeur d'achat",bn.valeurAchat?eu(bn.valeurAchat):null],["Surface",bn.surface?`${bn.surface} m²`:null],["Acquisition",bn.anneeAcquisition],im&&["Nb de lots",lb.length],["Notes",bn.notes]].filter(Boolean).map(([k,v])=>v?<Kv key={k} k={k} v={String(v)}/>:null)}</>}/>}
      </>)}

      {pg==="lot"&&lt&&(<>
        <div style={{background:LC[lt.typeLot]?.bg||C.gp,borderRadius:14,padding:"16px 20px",marginBottom:14,border:`1.5px solid ${C.br}`}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}>
            <div><div style={{display:"flex",gap:8,alignItems:"center",marginBottom:6}}><span style={{fontSize:28}}>{LM[lt.typeLot]?.emoji}</span><div><div style={{fontWeight:900,fontSize:18,color:LC[lt.typeLot]?.tx}}>{lt.nom}</div><div style={{fontSize:12,color:C.tm}}>{LM[lt.typeLot]?.label}</div></div></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{lt.etage&&<Bg ch={`Étage ${lt.etage}`}/>}{lt.surface&&<Bg ch={`${lt.surface} m²`}/>}{lt.nbPieces&&<Bg ch={`${lt.nbPieces} pièce${lt.nbPieces>1?"s":""}`}/>}{lt.loyer>0&&<Bg bg={C.gp} tc={C.g} ch={`${eu(lt.loyer)}/mois`}/>}</div></div>
            <div style={{textAlign:"right"}}><div style={{fontSize:22,fontWeight:900,color:stL.cf>=0?C.g:C.rd}}>{eu(stL.cf)}</div><div style={{fontSize:11,color:C.tm}}>cashflow {an}</div></div>
          </div>
        </div>
        <div style={{display:"flex",gap:4,marginBottom:16,flexWrap:"wrap"}}>{NL.map(([k,l])=>(<button key={k} onClick={()=>sSb(k)} style={{padding:"6px 12px",borderRadius:8,border:`1.5px solid ${sb===k?C.g:C.br}`,background:sb===k?C.g:C.wh,color:sb===k?"#fff":C.tx,fontWeight:600,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>{l}</button>))}</div>
        {sb==="apercu_l"&&(<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:14}}><Cd sx={{margin:0}} ch={<><St ch={`Performance ${an}`}/>{[["Revenus",eu(stL.R)],["Charges",eu(stL.CH)],["Cashflow",eu(stL.cf)],["Résultat fiscal",eu(stL.rs)]].map(([k,v])=><Kv key={k} k={k} v={v}/>)}</>}/><Cd sx={{margin:0}} ch={<><St ch="Rentabilité lot"/>{[["Valeur estimée",eu(lt.valeurEstimee)],["Loyer/mois",eu(lt.loyer)],["Loyer annuel",eu((lt.loyer||0)*12)],["Rdt brut",pt(lt.valeurEstimee>0?((lt.loyer||0)*12/lt.valeurEstimee*100):0)]].map(([k,v])=><Kv key={k} k={k} v={v}/>)}</>}/></div><div style={{display:"flex",gap:8}}><Bt ch="+ Revenu" onClick={()=>oM("aTx",{sens:"revenu",date:nw(),categorie:LM[lt.typeLot]?.rc||CR[0],lotId:lt.id})}/><Bt v="s" ch="+ Charge" onClick={()=>oM("aTx",{sens:"charge",date:nw(),categorie:CC[0],lotId:lt.id})}/></div></>)}
        {sb==="rev_l"&&<TxSec sx="revenu" txs={stL.rv} tot={stL.R} oA={()=>oM("aTx",{sens:"revenu",date:nw(),categorie:LM[lt.typeLot]?.rc||CR[0],lotId:lt.id})} oD={dTx} oE={eTx} an={an}/>}
        {sb==="chg_l"&&<TxSec sx="charge" txs={stL.ch} tot={stL.CH} dd={stL.dd} cp={stL.cp} oA={()=>oM("aTx",{sens:"charge",date:nw(),categorie:CC[0],lotId:lt.id})} oD={dTx} oE={eTx} an={an}/>}
        {sb==="loc_l"&&(<><div style={{display:"flex",justifyContent:"flex-end",marginBottom:10}}><Bt ch="+ Ajouter locataire" onClick={()=>oM("aLc",{typeContrat:"Bail meublé",statut:"Actif",lotId:lt.id})}/></div>{da.locataires.filter(l=>l.lotId===lId).length===0?<Cd sx={{textAlign:"center",padding:"36px"}} ch={<><div style={{fontSize:32}}>👤</div><div style={{color:C.tm}}>Aucun locataire.</div></>}/>:da.locataires.filter(l=>l.lotId===lId).map(l=><LcCard key={l.id} l={l} oD={dLc}/>)}</>)}
        {sb==="docs_l"&&<DocSec bId={bId} lId={lId} txs={da.transactions.filter(t=>t.lotId===lId)} da={da} sD={sD} ui_={ui} ts={tst}/>}
        {sb==="infos_l"&&<Cd ch={<><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}><div style={{fontWeight:800,fontSize:16}}>{lt.nom}</div><div style={{display:"flex",gap:8}}><Bt v="g" sx={{fontSize:12}} ch="✏️ Modifier" onClick={()=>oM("eLt",{...lt})}/><Bt v="d" sx={{fontSize:12}} ch="Supprimer" onClick={()=>{if(window.confirm("Supprimer ce lot ?"))dLt(lt.id);}}/></div></div>{[["Type",LM[lt.typeLot]?.label],["Étage",lt.etage],["Surface",lt.surface?`${lt.surface} m²`:null],["Nb pièces",lt.nbPieces],["Loyer cible",lt.loyer?eu(lt.loyer):null],["Valeur estimée",lt.valeurEstimee?eu(lt.valeurEstimee):null],["Notes",lt.notes]].map(([k,v])=>v?<Kv key={k} k={k} v={String(v)}/>:null)}</>}/>}
      </>)}
    </div>

    {mo&&(<div onClick={cM} style={{position:"fixed",inset:0,background:"rgba(0,0,0,.45)",zIndex:900,display:"flex",alignItems:"flex-end",justifyContent:"center"}}>
      <div onClick={e=>e.stopPropagation()} style={{background:C.wh,borderRadius:"18px 18px 0 0",padding:"24px 20px 36px",width:"100%",maxWidth:540,maxHeight:"90vh",overflowY:"auto"}}>
        <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:18}}>
          <div style={{fontWeight:800,fontSize:17,color:C.g}}>{{aBn:"Nouveau bien",eB:"Modifier le bien",aLt:"Nouveau lot",eLt:"Modifier le lot",aTx:fm.id?(fm.sens==="revenu"?"Modifier le revenu":"Modifier la charge"):(fm.sens==="revenu"?"Enregistrer un revenu":"Enregistrer une charge"),aLc:"Ajouter un locataire"}[mo]}</div>
          <button onClick={cM} style={{background:"none",border:"none",fontSize:20,cursor:"pointer",color:C.tm}}>✕</button>
        </div>
        {(mo==="aBn"||mo==="eB")&&<><Ip lb="Nom *" value={fm.nom||""} onChange={e=>sf("nom",e.target.value)}/><Ip lb="Adresse" value={fm.adresse||""} onChange={e=>sf("adresse",e.target.value)}/><Sl lb="Type" value={fm.type||TB[0]} onChange={e=>sf("type",e.target.value)}>{TB.map(t=><option key={t}>{t}</option>)}</Sl><Sl lb="Régime fiscal" value={fm.regime||RG[0]} onChange={e=>sf("regime",e.target.value)}>{RG.map(t=><option key={t}>{t}</option>)}</Sl><Ip lb="Valeur d'achat" type="number" value={fm.valeurAchat||""} onChange={e=>sf("valeurAchat",e.target.value)}/><Ip lb="Surface (m²)" type="number" value={fm.surface||""} onChange={e=>sf("surface",e.target.value)}/><Ip lb="Année d'acquisition" type="number" value={fm.anneeAcquisition||""} onChange={e=>sf("anneeAcquisition",e.target.value)}/><Ip lb="Notes" value={fm.notes||""} onChange={e=>sf("notes",e.target.value)}/><Bt ch="Enregistrer" onClick={sBn} sx={{width:"100%",padding:13,fontSize:15}}/></>}
        {(mo==="aLt"||mo==="eLt")&&<><Ip lb="Nom du lot *" placeholder="ex. Appt T3 2e droite" value={fm.nom||""} onChange={e=>sf("nom",e.target.value)}/><Sl lb="Type de lot *" value={fm.typeLot||"meuble"} onChange={e=>sf("typeLot",e.target.value)}>{TL.map(t=><option key={t.id} value={t.id}>{t.emoji} {t.label}</option>)}</Sl><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Ip lb="Étage" value={fm.etage||""} onChange={e=>sf("etage",e.target.value)}/><Ip lb="Nb de pièces" type="number" value={fm.nbPieces||""} onChange={e=>sf("nbPieces",e.target.value)}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Ip lb="Surface (m²)" type="number" value={fm.surface||""} onChange={e=>sf("surface",e.target.value)}/><Ip lb="Loyer cible (euro/mois)" type="number" value={fm.loyer||""} onChange={e=>sf("loyer",e.target.value)}/></div><Ip lb="Valeur estimée (euro)" type="number" value={fm.valeurEstimee||""} onChange={e=>sf("valeurEstimee",e.target.value)}/><Ip lb="Notes" value={fm.notes||""} onChange={e=>sf("notes",e.target.value)}/><Bt ch="Enregistrer le lot" onClick={sLt} sx={{width:"100%",padding:13,fontSize:15}}/></>}
        {mo==="aTx"&&<>
          <div style={{display:"flex",gap:6,marginBottom:14}}>{["revenu","charge"].map(s=>(<button key={s} onClick={()=>sF(f=>({...f,sens:s,categorie:s==="revenu"?CR[0]:CC[0]}))} style={{flex:1,padding:"9px 0",borderRadius:9,border:`2px solid ${fm.sens===s?(s==="revenu"?C.g:C.rd):C.br}`,background:fm.sens===s?(s==="revenu"?C.gp:C.rp):C.wh,fontWeight:700,fontSize:13,cursor:"pointer",fontFamily:"inherit",color:fm.sens===s?(s==="revenu"?C.g:C.rd):C.tm}}>{s==="revenu"?"💰 Revenu":"📉 Charge"}</button>))}</div>
          <Ip lb="Date *" type="date" value={fm.date||nw()} onChange={e=>sf("date",e.target.value)}/>
          <Sl lb="Catégorie *" value={fm.categorie||""} onChange={e=>sf("categorie",e.target.value)}>{(fm.sens==="revenu"?CR:CC).map(c=><option key={c}>{c}</option>)}</Sl>
          {lb.length>0&&(<Sl lb="Lot concerné" value={fm.lotId||""} onChange={e=>sf("lotId",e.target.value||null)}><option value="">— Immeuble / Parties communes</option>{lb.map(l=><option key={l.id} value={l.id}>{LM[l.typeLot]?.emoji} {l.nom}</option>)}</Sl>)}
          <Ip lb="Description / Tiers" value={fm.description||""} onChange={e=>sf("description",e.target.value)}/>
          <div style={{background:C.cr,border:`1.5px solid ${C.br}`,borderRadius:10,padding:"12px 14px",marginBottom:12}}>
            <div style={{fontSize:11,fontWeight:700,color:C.gl,textTransform:"uppercase",letterSpacing:".05em",marginBottom:10}}>Montant et TVA</div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:8}}>
              <div><label style={{display:"block",fontSize:11,fontWeight:700,color:C.gl,textTransform:"uppercase",letterSpacing:".05em",marginBottom:4}}>Montant TTC *</label><input type="number" step="0.01" min="0" placeholder="0.00" value={fm.montant||""} onChange={e=>{const ttc=parseFloat(e.target.value)||0;const tx=parseFloat(fm.tauxTVA)||0;const tv=tx>0?Math.round(ttc/(1+tx/100)*tx/100*100)/100:0;sF(f=>({...f,montant:e.target.value,tva:tv,ht:Math.round((ttc-tv)*100)/100}));}} style={{width:"100%",padding:"9px 11px",border:`1.5px solid ${C.br}`,borderRadius:8,fontSize:14,fontFamily:"inherit",color:C.tx,background:C.wh,outline:"none",boxSizing:"border-box"}}/></div>
              <div><label style={{display:"block",fontSize:11,fontWeight:700,color:C.gl,textTransform:"uppercase",letterSpacing:".05em",marginBottom:4}}>Taux TVA</label><select value={fm.tauxTVA||"0"} onChange={e=>{const tx=parseFloat(e.target.value)||0;const ttc=parseFloat(fm.montant)||0;const tv=tx>0?Math.round(ttc/(1+tx/100)*tx/100*100)/100:0;sF(f=>({...f,tauxTVA:e.target.value,tva:tv,ht:Math.round((ttc-tv)*100)/100}));}} style={{width:"100%",padding:"9px 11px",border:`1.5px solid ${C.br}`,borderRadius:8,fontSize:14,fontFamily:"inherit",color:C.tx,background:C.wh,outline:"none",boxSizing:"border-box"}}><option value="0">Sans TVA</option><option value="20">20 %</option><option value="10">10 %</option><option value="5.5">5,5 %</option><option value="2.1">2,1 %</option></select></div>
            </div>
            {(parseFloat(fm.tauxTVA)||0)>0&&(parseFloat(fm.montant)||0)>0&&(<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,background:C.wh,borderRadius:8,padding:"10px 12px",border:`1px solid ${C.br}`}}><div style={{textAlign:"center"}}><div style={{fontSize:10,color:C.tm,textTransform:"uppercase",marginBottom:2}}>HT</div><div style={{fontWeight:800,fontSize:16,color:C.g}}>{eu(fm.ht||0)}</div></div><div style={{textAlign:"center",borderLeft:`1px solid ${C.br}`}}><div style={{fontSize:10,color:C.tm,textTransform:"uppercase",marginBottom:2}}>TVA récupérable</div><div style={{fontWeight:800,fontSize:16,color:C.bl}}>{eu(fm.tva||0)}</div></div></div>)}
          </div>
          <Ip lb="Référence / N° de pièce" value={fm.ref||""} onChange={e=>sf("ref",e.target.value)}/>
          <Bt ch={fm.id?"Mettre à jour":"Enregistrer"} onClick={sTx} sx={{width:"100%",padding:13,fontSize:15}}/>
        </>}
        {mo==="aLc"&&<><Ip lb="Nom complet *" value={fm.nom||""} onChange={e=>sf("nom",e.target.value)}/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Ip lb="Email" type="email" value={fm.email||""} onChange={e=>sf("email",e.target.value)}/><Ip lb="Téléphone" type="tel" value={fm.tel||""} onChange={e=>sf("tel",e.target.value)}/></div>{lb.length>0&&(<Sl lb="Lot" value={fm.lotId||""} onChange={e=>sf("lotId",e.target.value||null)}><option value="">— Bien entier</option>{lb.map(l=><option key={l.id} value={l.id}>{LM[l.typeLot]?.emoji} {l.nom}</option>)}</Sl>)}<Sl lb="Type de contrat" value={fm.typeContrat||"Bail meublé"} onChange={e=>sf("typeContrat",e.target.value)}>{["Bail meublé","Bail nu","Bail professionnel équipé","Bail commercial","Convention d'occupation","Airbnb / saisonnier"].map(t=><option key={t}>{t}</option>)}</Sl><Sl lb="Statut" value={fm.statut||"Actif"} onChange={e=>sf("statut",e.target.value)}>{["Actif","Sorti","Préavis"].map(t=><option key={t}>{t}</option>)}</Sl><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Ip lb="Loyer mensuel" type="number" value={fm.loyer||""} onChange={e=>sf("loyer",e.target.value)}/><Ip lb="Dépôt de garantie" type="number" value={fm.depotGarantie||""} onChange={e=>sf("depotGarantie",e.target.value)}/></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Ip lb="Date d'entrée" type="date" value={fm.dateEntree||""} onChange={e=>sf("dateEntree",e.target.value)}/><Ip lb="Date de sortie" type="date" value={fm.dateSortie||""} onChange={e=>sf("dateSortie",e.target.value)}/></div><Ip lb="Notes" value={fm.notes||""} onChange={e=>sf("notes",e.target.value)}/><Bt ch="Ajouter le locataire" onClick={sLc} sx={{width:"100%",padding:13,fontSize:15}}/></>}
      </div>
    </div>)}
    {to&&<div style={{position:"fixed",bottom:24,left:"50%",transform:"translateX(-50%)",background:to.t==="err"?C.rd:C.g,color:"#fff",padding:"11px 22px",borderRadius:12,fontWeight:700,fontSize:14,boxShadow:"0 4px 20px rgba(0,0,0,.18)",zIndex:9999,animation:"ti .2s",whiteSpace:"nowrap"}}>{to.msg}</div>}
  </div>);
}

function TxSec({sx,txs,tot,dd,cp,ls=[],oA,oD,oE,an}){
  const iC=sx==="charge";
  const[cf,sCf]=useState("Toutes");
  const[vm,sVm]=useState(false);
  const cats=[...new Set(txs.map(t=>t.categorie))];
  const fil=cf==="Toutes"?txs:txs.filter(t=>t.categorie===cf);
  const tTVA=txs.filter(t=>(t.tva||0)>0).reduce((s,t)=>s+(t.tva||0),0);
  const pm={};
  [...fil].sort((a,b)=>b.date.localeCompare(a.date)).forEach(t=>{const k=t.date?.slice(0,7)||"";if(!pm[k])pm[k]=[];pm[k].push(t);});
  return(<><Cd ch={<>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}>
      <div><div style={{fontWeight:800,fontSize:18,color:iC?C.rd:C.g}}>{eu(tot)}</div><div style={{fontSize:11,color:C.tm}}>Total {an}</div>{iC&&dd!=null&&<div style={{fontSize:11,color:C.tm}}>dont {eu(dd)} déductibles · {eu(cp)} non déductible</div>}{tTVA>0&&<div style={{fontSize:11,color:C.bl,fontWeight:700}}>🔵 TVA {iC?"récupérable":"collectée"} : {eu(tTVA)}</div>}</div>
      <div style={{display:"flex",gap:8,alignItems:"center"}}><button onClick={()=>sVm(!vm)} style={{padding:"6px 12px",borderRadius:8,border:`1.5px solid ${C.g}`,background:vm?C.g:C.wh,color:vm?"#fff":C.g,fontWeight:600,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>{vm?"📋 Liste":"📅 Par mois"}</button><Bt ch="+ Ajouter" onClick={oA}/></div>
    </div>
    {cats.length>1&&<div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:10}}>{["Toutes",...cats].map(c=>(<button key={c} onClick={()=>sCf(c)} style={{padding:"4px 10px",borderRadius:20,border:`1.5px solid ${cf===c?C.g:C.br}`,background:cf===c?C.g:C.wh,color:cf===c?"#fff":C.tm,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:"inherit"}}>{c}</button>))}</div>}
    {fil.length===0?<div style={{textAlign:"center",color:C.tm,padding:"24px 0",fontSize:13}}>Aucun{iC?"e charge":" revenu"} pour {an}</div>
    :vm?Object.entries(pm).map(([mk,txm])=>{const[y,m]=mk.split("-");const tm=txm.reduce((s,t)=>s+t.montant,0);return(<div key={mk} style={{marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderBottom:`2px solid ${C.g}`,marginBottom:6}}><span style={{fontWeight:800,fontSize:14,color:C.g}}>{MF[parseInt(m)-1]} {y}</span><span style={{fontWeight:800,fontSize:14,color:iC?C.rd:C.g}}>{iC?"−":"+"} {eu(tm)}</span></div>{txm.map(t=><TxRow key={t.id} t={t} iC={iC} ls={ls} oE={oE} oD={oD}/>)}</div>);})
    :[...fil].sort((a,b)=>b.date.localeCompare(a.date)).map(t=><TxRow key={t.id} t={t} iC={iC} ls={ls} oE={oE} oD={oD}/>)}
  </>}/></>);}

function TxRow({t,iC,ls,oE,oD}){return(<div className="tr" style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",padding:"9px 4px",borderBottom:`1px solid ${C.br}`,borderRadius:6,transition:"background .15s",gap:8}}><div style={{flex:1}}><div style={{fontWeight:600,fontSize:13,marginBottom:2}}>{t.description||t.categorie}</div><div style={{display:"flex",gap:5,flexWrap:"wrap",alignItems:"center"}}><Bg bg={iC?C.cr2:C.gp} tc={iC?C.tm:C.g} ch={t.categorie}/><span style={{fontSize:11,color:C.tm}}>📅 {fd(t.date)}</span>{t.lotId&&ls.length>0&&(()=>{const l=ls.find(x=>x.id===t.lotId);return l?<span style={{fontSize:10,color:C.bl}}>📦 {l.nom}</span>:null;})()}{t.ref&&<span style={{fontSize:10,color:C.tm}}>#{t.ref}</span>}{iC&&t.categorie==="Crédit immobilier - capital"&&<span style={{fontSize:10,color:C.rd,fontWeight:700}}>Non déductible</span>}{(t.tva||0)>0&&<span style={{fontSize:10,color:C.bl,fontWeight:700,background:C.bp,padding:"1px 6px",borderRadius:10}}>TVA {t.tauxTVA}% · {eu(t.tva)}</span>}</div></div><div style={{display:"flex",alignItems:"center",gap:6,flexShrink:0}}><span style={{fontWeight:800,fontSize:14,color:iC?C.rd:C.g}}>{iC?"−":"+"} {eu(t.montant)}</span><button onClick={()=>oE(t)} style={{background:C.gp,border:"none",borderRadius:6,padding:"4px 8px",fontSize:11,cursor:"pointer",color:C.g,fontWeight:700}}>✏️</button><button onClick={()=>oD(t.id)} style={{background:"none",border:"none",color:C.tm,cursor:"pointer",fontSize:14,padding:2}}>✕</button></div></div>);}

function LcCard({l,lt,oD}){return(<Cd ch={<><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div style={{flex:1}}><div style={{fontWeight:800,fontSize:15,marginBottom:4}}>{l.nom}</div>{lt&&<div style={{fontSize:12,color:C.bl,marginBottom:4}}>📦 {lt.nom}</div>}{l.email&&<div style={{fontSize:12,color:C.tm,marginBottom:2}}>✉️ {l.email}</div>}{l.tel&&<div style={{fontSize:12,color:C.tm,marginBottom:6}}>📞 {l.tel}</div>}<div style={{display:"flex",gap:5,flexWrap:"wrap"}}><Bg ch={l.typeContrat}/><Bg bg={l.statut==="Actif"?C.gp:C.rp} tc={l.statut==="Actif"?C.g:C.rd} ch={l.statut}/>{l.loyer&&<Bg bg={C.dp} tc={C.gd} ch={`${eu(l.loyer)}/mois`}/>}</div>{l.dateEntree&&<div style={{fontSize:11,color:C.tm,marginTop:6}}>Entrée : {fd(l.dateEntree)}{l.dateSortie?` · Sortie : ${fd(l.dateSortie)}`:""}</div>}</div><button onClick={()=>oD(l.id)} style={{background:"none",border:"none",color:C.rd,cursor:"pointer",fontSize:18,padding:4}}>✕</button></div></>}/>);}

function TvaSec({txs,an}){const tA=txs.filter(t=>String(t.date).startsWith(String(an)));const cT=tA.filter(t=>t.sens==="charge"&&(t.tva||0)>0);const rT=tA.filter(t=>t.sens==="revenu"&&(t.tva||0)>0);const tD=cT.reduce((s,t)=>s+(t.tva||0),0);const tC=rT.reduce((s,t)=>s+(t.tva||0),0);const so=tC-tD;return(<><Cd sx={{background:`linear-gradient(135deg,${C.bl},#1a5276)`,border:"none"}} ch={<><div style={{fontSize:11,fontWeight:700,color:"rgba(255,255,255,.65)",textTransform:"uppercase",letterSpacing:".07em",marginBottom:10}}>Bilan TVA — {an}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:4}}>{[["TVA collectée",eu(tC),"#a8d5b5"],["TVA déductible",eu(tD),"#f5c6c0"],["Solde",eu(so),so>=0?"#f5c6c0":"#a8d5b5"]].map(([l,v,c])=>(<div key={l} style={{textAlign:"center",padding:"8px 4px"}}><div style={{fontSize:18,fontWeight:800,color:c}}>{v}</div><div style={{fontSize:10,color:"rgba(255,255,255,.6)",marginTop:3,textTransform:"uppercase"}}>{l}</div></div>))}</div></>}/><Cd ch={<><St ch="TVA déductible"/>{cT.length===0?<div style={{textAlign:"center",color:C.tm,padding:"20px"}}>Aucune charge avec TVA pour {an}</div>:cT.map(t=>(<div key={t.id} style={{display:"flex",justifyContent:"space-between",padding:"7px 0",borderBottom:`1px solid ${C.br}`,fontSize:13}}><div><div style={{fontWeight:600}}>{t.description||t.categorie}</div><div style={{fontSize:11,color:C.tm}}>{fd(t.date)} · HT : {eu(t.ht||0)} · TVA {t.tauxTVA}%</div></div><span style={{fontWeight:800,color:C.bl}}>{eu(t.tva)}</span></div>))}<div style={{display:"flex",justifyContent:"space-between",padding:"10px 0 0"}}><span style={{fontWeight:800}}>Total TVA déductible</span><span style={{fontWeight:800,color:C.bl,fontSize:15}}>{eu(tD)}</span></div></>}/><Cd sx={{background:"#f0f4ff",border:`1px solid ${C.bl}`}} ch={<><div style={{fontSize:12,fontWeight:700,color:C.bl,marginBottom:8}}>💡 Déclaration CA3</div><div style={{fontSize:13,lineHeight:1.9}}>TVA collectée (L.08) : <strong>{eu(tC)}</strong><br/>TVA déductible (L.20) : <strong>{eu(tD)}</strong><br/>{so>=0?"TVA à payer":"Crédit TVA"} (L.23) : <strong style={{color:so>=0?C.rd:C.g}}>{eu(Math.abs(so))}</strong></div></>}/></>);}

function DocSec({bId,lId,txs,da,sD,ui_,ts}){const[lk,sLk]=useState("");const docs=(da.documents||[]).filter(d=>d.bienId===bId&&(lId?d.lotId===lId:true));function hF(files){Array.from(files).forEach(f=>{if(f.size>5*1024*1024){ts("Max 5 Mo","err");return;}const r=new FileReader();r.onload=e=>{const d={id:ui_(),bienId:bId,lotId:lId||null,txId:lk||null,nom:f.name,type:f.type,data:e.target.result,date:nw()};sD(da=>({...da,documents:[...(da.documents||[]),d]}));ts("Ajouté");};r.readAsDataURL(f);});}function dD(id){sD(da=>({...da,documents:(da.documents||[]).filter(x=>x.id!==id)}));ts("Supprimé","err");}const tC=txs.filter(t=>t.sens==="charge");return(<><Cd ch={<><div onDrop={e=>{e.preventDefault();hF(e.dataTransfer.files);}} onDragOver={e=>e.preventDefault()} style={{border:`2px dashed ${C.br}`,borderRadius:12,padding:"24px 20px",textAlign:"center",marginBottom:14,cursor:"pointer",background:C.cr}} onClick={()=>document.getElementById(`di${bId}${lId||""}`).click()}><div style={{fontSize:32,marginBottom:6}}>📎</div><div style={{fontWeight:700,fontSize:14,color:C.g,marginBottom:4}}>Cliquer ou glisser un fichier</div><div style={{fontSize:12,color:C.tm}}>Photos tickets · Factures PDF (max 5 Mo)</div><input id={`di${bId}${lId||""}`} type="file" accept="image/*,application/pdf" multiple style={{display:"none"}} onChange={e=>hF(e.target.files)}/></div>{tC.length>0&&<Sl lb="Associer à une dépense" value={lk} onChange={e=>sLk(e.target.value)}><option value="">— Aucune dépense liée</option>{tC.map(t=><option key={t.id} value={t.id}>{t.date} · {t.categorie} · {eu(t.montant)}</option>)}</Sl>}</>}/>{docs.length===0?<Cd sx={{textAlign:"center",padding:"36px"}} ch={<><div style={{fontSize:36}}>🗂</div><div style={{color:C.tm,marginTop:8}}>Aucun document.</div></>}/>:docs.map(d=>(<Cd key={d.id} ch={<div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:48,height:48,borderRadius:8,overflow:"hidden",flexShrink:0,background:C.cr2,display:"flex",alignItems:"center",justifyContent:"center"}}>{d.type?.startsWith("image/")?<img src={d.data} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/>:<span style={{fontSize:24}}>📄</span>}</div><div style={{flex:1,minWidth:0}}><div style={{fontWeight:600,fontSize:13,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{d.nom}</div><div style={{fontSize:11,color:C.tm}}>{d.date}</div></div><div style={{display:"flex",gap:6}}><a href={d.data} download={d.nom} style={{background:C.cr2,borderRadius:7,padding:"5px 10px",fontSize:12,color:C.tx,fontWeight:700,textDecoration:"none"}}>⬇️</a><button onClick={()=>dD(d.id)} style={{background:"none",border:"none",color:C.rd,cursor:"pointer",fontSize:16}}>✕</button></div></div>}/>))}</>);}

function FiscSec({bn,stB,an}){const{R:lo,dd,cp,it,rs}=stB;const rg=bn.regime||"";const is=cIS(rs);const[dv,sDv]=useState(0);const isIS=rg.includes("IS")||rg.includes("SARL");if(isIS)return(<><Cd sx={{border:`2px solid ${C.g}`}} ch={<><div style={{fontWeight:800,color:C.g,marginBottom:4}}>Compte de résultat — {an}</div><div style={{fontSize:12,color:C.tm,marginBottom:14}}>{bn.nom} · <strong>{rg}</strong></div><Fl lb="Loyers et produits" vl={eu(lo)} bd/><Dv/><Fl lb="Charges déductibles" vl={eu(dd)} bd/>{cp>0&&<Fl lb="Capital (non déductible)" vl={eu(cp)} mt/>}<Dv/><Fl lb={`Résultat ${rs>=0?"bénéficiaire":"déficitaire"}`} vl={eu(rs)} bd co={rs>=0?C.g:C.rd}/></>}/><Cd sx={{border:`1.5px solid ${C.bl}`}} ch={<><div style={{fontWeight:800,color:C.bl,marginBottom:12}}>🏛 Impôt sur les Sociétés</div>{rs<=0?<div style={{background:C.gp,borderRadius:8,padding:"12px",fontSize:13,color:C.g}}>Résultat déficitaire — aucun IS dû. Report illimité.</div>:<><Fl lb="Tranche 15% (jusqu'à 42 500)" vl={eu(Math.min(rs,42500)*0.15)} in={true}/>{rs>42500&&<Fl lb="Tranche 25% (au-delà)" vl={eu((rs-42500)*0.25)} in={true}/>}<Dv/><Fl lb="IS total estimé" vl={eu(is)} bd co={C.bl}/><Fl lb="Résultat net après IS" vl={eu(rs-is)} bd co={rs-is>=0?C.g:C.rd}/></>}</>}/>{rs>0&&<Cd ch={<><div style={{fontWeight:800,color:C.gd,marginBottom:12}}>💸 Simulation dividendes</div><Ip lb="Montant à distribuer (euro)" type="number" value={dv} onChange={e=>sDv(parseFloat(e.target.value)||0)}/><Fl lb="Flat tax PFU 30%" vl={eu(dv*0.30)}/><Fl lb="Dividendes nets" vl={eu(Math.max(0,dv*0.70))} bd co={C.g}/></>}/> }<Cd sx={{background:"#f0f4ff",border:`1px solid ${C.bl}`}} ch={<><div style={{fontSize:12,fontWeight:700,color:C.bl,marginBottom:8}}>Formulaire 2065</div><div style={{fontSize:13,lineHeight:1.9}}>CA : <strong>{eu(lo)}</strong> · IS : <strong>{eu(is)}</strong> · Acomptes trimestriels : <strong>{eu(is/4)}</strong></div></>}/></>);
  return(<><Cd sx={{border:`2px solid ${C.g}`}} ch={<><div style={{fontWeight:800,color:C.g,marginBottom:4}}>Récapitulatif fiscal {an}</div><div style={{fontSize:12,color:C.tm,marginBottom:14}}>Régime : <strong>{rg}</strong></div><Fl lb="Revenus bruts" vl={eu(lo)} bd/><Dv/>{it>0&&<Fl lb="Intérêts d'emprunt" vl={eu(it)} in={true}/>}{dd-it>0&&<Fl lb="Autres charges déductibles" vl={eu(dd-it)} in={true}/>}<Dv/><Fl lb="Total déductible" vl={eu(dd)} bd/>{cp>0&&<Fl lb="Capital (non déductible)" vl={eu(cp)} mt/>}<Dv/><Fl lb={`Résultat ${rs>=0?"bénéficiaire":"déficitaire"}`} vl={eu(rs)} bd co={rs>=0?C.g:C.rd}/></>}/><Cd sx={{background:C.gp,border:`1px solid ${C.g}`}} ch={<>{rg.includes("2044")&&<div style={{fontSize:13,lineHeight:1.8}}><b>Formulaire 2044</b><br/>Ligne 211 : <strong>{eu(lo)}</strong> · Ligne 221 : <strong>{eu(it)}</strong> · Ligne 229 : <strong>{eu(dd-it)}</strong><br/>Résultat : <strong style={{color:rs>=0?C.g:C.rd}}>{eu(rs)}</strong></div>}{rg.includes("BIC")&&<div style={{fontSize:13,lineHeight:1.8}}><b>Liasse BIC</b><br/>CA : <strong>{eu(lo)}</strong> · Charges : <strong>{eu(dd)}</strong> · Résultat : <strong style={{color:rs>=0?C.g:C.rd}}>{eu(rs)}</strong></div>}{rg.includes("Micro-foncier")&&<div style={{fontSize:13}}><b>Case 4BE</b> : <strong>{eu(lo)}</strong> (abattement 30%)</div>}{rg.includes("Micro-BIC")&&<div style={{fontSize:13}}><b>2042 C PRO</b> : <strong>{eu(lo)}</strong> (abattement 50%)</div>}</>}/></>);}
